import Head from "next/head";
import Image from "next/image";
import { PaperAirplaneIcon } from "@heroicons/react/24/solid";

export default function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen bg-black1">
        <h1 className="text-7xl text-font-white ">Starter Template</h1>
      </div>
    </>
  );
}
